---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ginne.
--- DateTime: 2020/5/7 11:19
---
local basic = require("matrixbasic")
N = 4
local A = torch.Tensor({{0,1,0},
                        {0,0,1},
                        {0,0,0}})
local B = torch.Tensor({{0},{0},{1}})

--local A = torch.Tensor({{1,0,1,0},
--                        {0,1,-1,0},
--                        {0,1,0,0},
--                        {1,1,0,1}})
--local B = torch.Tensor({{1,0},{0,0},{-1,1},{0,0}})

local C = B
for i=1,A:size()[1]-1,1 do
    local temp = A
    for j=1,i-1,1 do
        temp = temp * A
    end
    C = torch.cat(C,temp*B,2)
end
print(C)
print(basic.rank(C))