---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ginne.
--- DateTime: 2020/3/3 18:34
---

local basic = require("matrix_basic")
--x = torch.ceil(10*torch.rand(4, 3))
x = torch.Tensor(3,3)
x[3] = torch.Tensor({1,2,3})
x[2] = torch.Tensor({2,2,3})
x[1] = torch.Tensor({7,8,9})
y = torch.Tensor(1,1)
y[1] = torch.Tensor({1})
print(5*x)
print(basic.rank(x))

